default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: food_ordering_system_development

  test:
  <<: *default
  database: food_ordering_system_test